### ISSUE TITLE
Metrics pass over FTL

### ISSUE THREAD

**Issue by alecthomas** [block/ftl#1988]
FTL needs to be instrumented sufficiently for production. This ticket tracks all the tasks, in the order we should do them in.

* [x] https://github.com/TBD54566975/ftl/issues/2020
* [ ] https://github.com/TBD54566975/ftl/issues/2022
* [x] [Depends on 2020, 2021] https://github.com/TBD54566975/ftl/issues/2021
* [x] [Depends on 2020] https://github.com/TBD54566975/ftl/issues/2023
* [x] [Depends on 2020] https://github.com/TBD54566975/ftl/issues/2024
* [x] https://github.com/TBD54566975/ftl/issues/2025
    * Once done, we'll need to create issues for all the signals enumerated for this issue. The new issues for implementing those signals should be added to this list.
* [x] https://github.com/TBD54566975/ftl/issues/2194
* [x] https://github.com/TBD54566975/ftl/issues/2205
* [ ] https://github.com/TBD54566975/ftl/issues/2203
* [x] https://github.com/TBD54566975/ftl/issues/2258
* [ ] https://github.com/TBD54566975/ftl/issues/2286
* [x] https://github.com/TBD54566975/ftl/issues/2285
* [ ] https://github.com/TBD54566975/ftl/issues/2303
* [ ] [LOW PRI] https://github.com/TBD54566975/ftl/issues/2026
* [ ] [LOW PRI] https://github.com/TBD54566975/ftl/issues/2027

**Comment by bradleydwyer** [comment]
Consider how to test this locally without deployment / deployment of FTL.

**Comment by deniseli** [comment]
Initial breakdown of tasks that we'll sync with the team on:

1. Implement `just otel` - should run [otel collector](https://opentelemetry.io/docs/collector/) in a docker container to collect local logs/metrics/traces/spans and show the stream as they come in in the terminal tab. This way, we can run `ftl dev`, trigger the events we plan to log, and see them come through the terminal window in real(ish) time.
1. Chat with PFI about what they need to log
1. Make sure everything existing actually WAI
1. Add these attributes to all signals:
    1. `project_name`: from `ftl-project.toml`
    1. `is_user_service`: We have the `serviceName` set here, which currently will be one of `ftl-controller`, `ftl-runner`, or `<module name>`. Technically, we could use `ftl-controller || ftl-runner` but it would be good to be a bit more explicit.
        1. Add bool flag `isInternal` to `observability.Config` so that `Init`’s callers can configure whether it’s user code or not.
    1. `trace_id`: do we know if the `trace_id` that otel provides is already instrumented correctly such that it can be used to trace verb-to-verb calls like the `trace_id` in our request headers, or better yet if they’re actually the same `trace_id`? If not, then we need to make the one in the request headers available.
        1. Q: should we persist all the header values to attrs? A: we should check if any is done by default. Also, check if there’s any sensitive data (e.g. auth tokens)
1. Plan out new signals + their attributes (incl. pubsub as described in the ticket desc)

**Comment by deniseli** [comment]
Just finished updating the ticket description. Everyone, feel free to assign tasks to yourself. I'll take the first one. Please do not take the two marked low priority until the others are closed (and maybe not even then!)

The original PubSub notes in the ticket description are now in https://github.com/TBD54566975/ftl/issues/2025, along with @bradleydwyer 's reminders (feel free to add more in that ticket ;) )
