### ISSUE TITLE
Infrastructure Roadmap

### ISSUE THREAD

**Issue by bradleydwyer** [block/ftl#2441]
### Next

- [x] #2538
- [ ]  #2449

### Backlog
**Infrastructure Resources**

- [ ]  MySQL support (boooooo). https://github.com/TBD54566975/ftl/labels/P1
- [ ]  Kafka support https://github.com/TBD54566975/ftl/labels/P2

**Pending Customer New infrastructure abstractions: https://github.com/TBD54566975/ftl/labels/P3**

- [ ]  KV store (small values)
- [ ]  Blob store (large values/files with streaming support, eg. S3)
- [ ]  Cache support
- [ ]  KMS (or Tink directly?)

**Customer deployment of FTL (minimally automated) https://github.com/TBD54566975/ftl/labels/P1**

- [ ]  FTL release management
- [ ]  Data migrations
- [ ]  Pending Customer As we build out infrastructure support on AWS, should we support GCP as well? This will a) keep us honest and b) we will likely have ML customers on GCP https://github.com/TBD54566975/ftl/labels/P3
- [ ]  Cross-check against GCP APIs as we implement AWS primitives

**Pubsub**

- [ ]  Batching https://github.com/TBD54566975/ftl/labels/P2
- [ ]  Partitioning https://github.com/TBD54566975/ftl/labels/P2
- [ ]  Commands to manage topics/subscriptions https://github.com/TBD54566975/ftl/labels/P2
- [ ]  Option to start at beginning of topic, or from time of subscription, or other point? https://github.com/TBD54566975/ftl/labels/P3
- [ ]  Retention policy https://github.com/TBD54566975/ftl/labels/P1
- [ ]  Kafka https://github.com/TBD54566975/ftl/labels/P2
