### ISSUE TITLE
Core Roadmap

### ISSUE THREAD

**Issue by alecthomas** [block/ftl#2442]
### Next
- [ ] #2450
- Once design is done, think about priority of implementation re. customer
- [ ] Tech debt:
  - [ ] Convert everything to async calls https://github.com/TBD54566975/ftl/labels/P1 @safeer
  - [ ] #2451
  - [x] Split VerbService from ModuleContext related methods https://github.com/TBD54566975/ftl/labels/P1
  - [x] #2452
### Backlog
 

- [x] #2530
- [ ]  Design hot reload system for languages https://github.com/TBD54566975/ftl/labels/P1
  - [ ] User Documentation
    - [ ] Playbooks
    - [ ]  How to do X in FTL, runbooks etc. https://github.com/TBD54566975/ftl/labels/P3
- [ ]  Design for data/schema/module versioning/migration (huge topic) https://github.com/TBD54566975/ftl/labels/P1
    - [ ]  Versioning verbs
    - [ ]  Persistent data migration
- [x] #2977
- [ ]  Forward/backward compatibility schema checks https://github.com/TBD54566975/ftl/labels/P3
- [ ]  Ability to extend FTL using FTL. eg. pubsub or cron implemented as an FTL "system" module https://github.com/TBD54566975/ftl/labels/P3
- [ ]  Pending Customer How to distribute compiled module runtime code - package server? Codegen? https://github.com/TBD54566975/ftl/labels/P3
- [ ]  Design Typed HTTP ingress path/query params https://github.com/TBD54566975/ftl/labels/P2
