### ISSUE TITLE
Console graph rewrite epic

### ISSUE THREAD

**Issue by deniseli** [block/ftl#2695]
* [ ] https://github.com/TBD54566975/ftl/issues/2459
* [ ] https://github.com/TBD54566975/ftl/issues/2692
* [ ] https://github.com/TBD54566975/ftl/issues/2693
* [ ] https://github.com/TBD54566975/ftl/issues/2694
